### PR TITLE
Update gem version

### PR DESCRIPTION
**Pull request by Vasu1105**

### CODE REVIEW

**Comment by Vasu1105** [comment]
@matti Yes it's failing but I am not sure what's failing as I am not aware of the environment.

**Comment by Vasu1105** [comment]
I think it's failing on ruby 2.6. if I am not wrong

**Comment by matti** [comment]
It fails with all supported rubies. the action just tests it first with 2.6.

I'll change the ci to run all.

Anyway, I don't know either, but master passes and this is prob related to https://github.com/k8s-ruby/k8s-ruby/pull/29 somehow

**Comment by matti** [comment]
@Vasu1105 now CI builds all versions, if you push/trigger you'll see that also ruby 3.0 fails

**Comment by Vasu1105** [comment]
@matti  failing just on 2.6

**Comment by matti** [comment]
@Vasu1105 thank you!

Please accept https://github.com/k8s-ruby/k8s-ruby/invitations as maintainer and send me your rubygems email so that I can allow you to publish it

**Comment by matti** [comment]
@Vasu1105 actually 2.6 still fails with, the CI job incorrectly returns ok

```console
rspec-2.6_1  | Fetching gem metadata from https://rubygems.org/.........
rspec-2.6_1  | Your bundle is locked to dry-struct (1.5.2) from rubygems repository
rspec-2.6_1  | https://rubygems.org/ or installed locally, but that version can no longer be
rspec-2.6_1  | found in that source. That means the author of dry-struct (1.5.2) has removed
rspec-2.6_1  | it. You'll need to update your bundle to a version other than dry-struct (1.5.2)
rspec-2.6_1  | that hasn't been removed in order to install.
k8s-ruby_rspec-2.6_1 exited with code 7
```

**Pull request merged**
