### PR TITLE
Fix Ruby 2.7 warnings (required updating to the latest dry-types version)

### PR DESCRIPTION
**Pull request by elthariel**
This PR upgrades to the latest dry-types to get rid of the ruby 2.7 keyword argument warning. It also fixes the spec to remove most warning. A few remain that aren't fixed in rspec and recursive open struct

### CODE REVIEW

**Comment by matti** [comment]
@elthariel I invited you to write to the repository. If you still have energy, please merge these.

**Review by matti — APPROVED** [review]

**Comment by matti** [comment]
merging anyway, nobody maintains this gem, trying to get this working with 3.x now

**Comment by matti** [comment]
didn't work, reverted

**Comment by dwillett** [comment]
Hey @matti - I was looking at changes needed to support 3.0.x as well, wondering what remaining issues you were seeing?

**Comment by matti** [comment]
dry-types / dry-structs upgrade, the API has changed

**Comment by dwillett** [comment]
More so than what was accounted for in this reverted merge? I made similar changes in my fork here to bring it up to compatibility and my unit tests are passing. Wondering if there are additional errors I'm not seeing: https://github.com/dwillett/k8s-ruby/commit/c39e7de737a059c6618e6bca39f39fd84371267e

**Comment by matti** [comment]
@dwillett the error was that `Gemfile.lock` is not in version control and therefore I couldn't bundle.

merged your master and released as 0.12.0

also sent you an invite to become a maintainer: https://github.com/k8s-ruby/k8s-ruby/invitations

**Pull request merged**
